### ISSUE TITLE
Unable to Create STG

### ISSUE THREAD

**Issue by RyanMBess** [eiddor/ise-automation-ansible#1]
Below is the full dump of the error.  Any help would be appreciated.

ansible-playbook [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ryan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ryan/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ryan/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/ryan/ansible_ise/ise-automation-ansible-main/hosts as it did not pass its verify_file() method
script declined parsing /home/ryan/ansible_ise/ise-automation-ansible-main/hosts as it did not pass its verify_file() method
auto declined parsing /home/ryan/ansible_ise/ise-automation-ansible-main/hosts as it did not pass its verify_file() method
Parsed /home/ryan/ansible_ise/ise-automation-ansible-main/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: 06_create-sgts.yaml **********************************************************************************************************************************************************************************************************************
1 plays in 06_create-sgts.yaml
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'

PLAY [ise_servers] *********************************************************************************************************************************************************************************************************************************
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'
META: ran handlers
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'

TASK [Create] **************************************************************************************************************************************************************************************************************************************
task path: /home/ryan/ansible_ise/ise-automation-ansible-main/06_create-sgts.yaml:19
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'acct', 'sgtdesc': 'Accounting SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "Accounting SGT for SDA",
        "sgtname": "acct"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'Campus_Quarantine', 'sgtdesc': 'Campus_Quarantine SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "Campus_Quarantine SGT for SDA",
        "sgtname": "Campus_Quarantine"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'finance', 'sgtdesc': 'Finance SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "Finance SGT for SDA",
        "sgtname": "finance"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'hr', 'sgtdesc': 'HR SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "HR SGT for SDA",
        "sgtname": "hr"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'PCI', 'sgtdesc': 'PCI SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "PCI SGT for SDA",
        "sgtname": "PCI"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"

**Comment by eiddor** [comment]
Hey there - I haven't tested this repo out in a while, but let me try to help.

Can you tell me what version of ISE you're running?  I had to update for ISE 3.1p1, so I'm not sure how well that will work with the DevNet instance that I originally developed this on.

Ansible isn't very forthcoming about failure reasons, but it seems to be an API permissions error, so make sure that you've enabled all of the APIs in ISE's settings.

**Comment by RyanMBess** [comment]
hey man.  Here's what i'm running 3.1.0.518 which appears to not be patch 1.  Let me update to patch 1.  Should have caught that.

**Comment by RyanMBess** [comment]
OK just updated to patch 3.  I'm running this in my virtual home server to learn ISE.    

ise1/ryan# show version

Cisco Application Deployment Engine OS Release: 3.1
ADE-OS Build Version: 3.1.0.135
ADE-OS System Architecture: x86_64

Copyright (c) 2005-2021 by Cisco Systems, Inc.
All rights reserved.
Hostname: ise1


Version information of installed applications
---------------------------------------------

Cisco Identity Services Engine
---------------------------------------------
Version      : 3.1.0.518
Build Date   : Mon Aug  9 16:28:55 2021
Install Date : Fri Jul 15 08:16:56 2022

Cisco Identity Services Engine Patch
---------------------------------------------
Version      : 3
Install Date : Wed Aug 24 08:47:57 2022


here's the error.  Looks the same error.  Thoughts?  


ryan@ANSIBLE-ISE:~/ansible_ise/ise-automation-ansible-main$ ansible-playbook -i hosts 06_create-sgts.yaml -vvv
ansible-playbook [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ryan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ryan/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ryan/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/ryan/ansible_ise/ise-automation-ansible-main/hosts as it did not pass its verify_file() method
script declined parsing /home/ryan/ansible_ise/ise-automation-ansible-main/hosts as it did not pass its verify_file() method
auto declined parsing /home/ryan/ansible_ise/ise-automation-ansible-main/hosts as it did not pass its verify_file() method
Parsed /home/ryan/ansible_ise/ise-automation-ansible-main/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: 06_create-sgts.yaml **********************************************************************************************************************************************************************************************************************
1 plays in 06_create-sgts.yaml
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'

PLAY [ise_servers] *********************************************************************************************************************************************************************************************************************************
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'
META: ran handlers
Read vars_file 'credentials.yaml'
Read vars_file 'policy.yaml'

TASK [Create] **************************************************************************************************************************************************************************************************************************************
task path: /home/ryan/ansible_ise/ise-automation-ansible-main/06_create-sgts.yaml:19
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'acct', 'sgtdesc': 'Accounting SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "Accounting SGT for SDA",
        "sgtname": "acct"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'Campus_Quarantine', 'sgtdesc': 'Campus_Quarantine SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "Campus_Quarantine SGT for SDA",
        "sgtname": "Campus_Quarantine"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'finance', 'sgtdesc': 'Finance SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "Finance SGT for SDA",
        "sgtname": "finance"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'hr', 'sgtdesc': 'HR SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "HR SGT for SDA",
        "sgtname": "hr"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}
The full traceback is:
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 207, in exec
    response = func(**params)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/api/v3_1_patch_1/security_groups.py", line 856, in create_security_group
    _api_response = self._session.post(endpoint_full_url, params=_params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 643, in post
    response = self.request('POST', url, erc, 0, params=params,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 546, in request
    return self.request(method, url, erc, 1, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/restsession.py", line 523, in request
    check_response_code(response, erc,
  File "/home/ryan/.local/lib/python3.10/site-packages/ciscoisesdk/misc.py", line 62, in check_response_code
    raise ApiError(response, **kwargs)
ciscoisesdk.exceptions.ApiError: [403] - The request is understood, but it has been refused or access is not allowed.
Check ApiError.additional_data for more info.

failed: [10.10.10.20] (item={'sgtname': 'PCI', 'sgtdesc': 'PCI SGT for SDA'}) => {
    "ansible_loop_var": "item",
    "item": {
        "sgtdesc": "PCI SGT for SDA",
        "sgtname": "PCI"
    },
    "msg": "An error occured when executing operation. The error was: [403] - The request is understood, but it has been refused or access is not allowed.\nCheck ApiError.additional_data for more info.\n"
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************
10.10.10.20                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by eiddor** [comment]
It looks like a permissions error, but you can never be sure with Ansible.

Can you send a screenshot of this page: Administration | Settings | API Settings | API Service Settings

**Comment by RyanMBess** [comment]
I'm also pinging some of the cisco guys who are trying to sell us this product as well.  


I can't figure out how to send print screens but ers and open API are enabled.  The account I'm using is a superadmin

**Comment by eiddor** [comment]
If you go to the API Gateway Settings, do you see this enabled?

![image](https://user-images.githubusercontent.com/7586731/186465791-cb2d639e-a8f4-4b32-8fdf-b6fc37dd3c3b.png)

**Comment by RyanMBess** [comment]
Yup i see exactly that.  FYI:  other API calls work.  So far it's just the STG's that are not.

**Comment by eiddor** [comment]
Hmmm interesting - Unfortunately, instance is a bit of a mess right now, so I won't be able to test things out right now.  :-( 

The SGT playbook is one of the simpler ones, so I'm sure it's going to be something easy.  Do you happen to have ISE and DNAC integrated already?

**Comment by RyanMBess** [comment]
nope...just a home virtual ISE environment.

**Comment by eiddor** [comment]
I just tested here with my instance and it works -  I even updated to the latest versions of Ansible, ISE SDK, and the collection.  Did you modify `policy.yaml` at all?

**Comment by RyanMBess** [comment]
hmmm i'll take a look at things.

**Comment by RyanMBess** [comment]
only thing i can think of is i have 2 matrix's.  Let me remove one so there's only 1 place for the sgt to be used.

**Comment by eiddor** [comment]
Oh, yes, so there's a known limitation in ISE's API where it only has access to one matrix (there's a whole history there that I don't want to get into here).  

That _might_ be the problem.  Let me know!

**Comment by RyanMBess** [comment]
Yup that was def it.  As soon as i removed the failback matrix, in like flint!   How involved are you in this product / API.  I'm working on a one of a kind solution that from what i'm told from our Cisco partners, it aint been done before.  It has to do with non standard equipment, Service now, and just in time provision for those non standard equipment via ansible and ISE.

**Comment by eiddor** [comment]
Excellent - Glad you got it figured out!

>How involved are you in this product / API

I'm not involved in it at all - I'm on the sales side, so I wouldn't even know who to point you to.
